package t3b.pv.cierraturno.dao;

import java.sql.Connection;
import java.util.List;

import t3b.pv.cierraturno.dto.ArqueoCierraTurnoDto;
import t3b.pv.cierraturno.dto.CancelacionesDto;
import t3b.pv.cierraturno.dto.CancelacionesEncDto;
import t3b.pv.cierraturno.dto.CierraTurnoDto;
import t3b.pv.cierraturno.dto.CierraTurnoKardex;
import t3b.pv.cierraturno.dto.DevolucionesDto;
import t3b.pv.cierraturno.dto.DevolucionesEncabezado;
import t3b.pv.cierraturno.dto.DtoTurnoActivo;
import t3b.pv.cierraturno.dto.EValeLogDto;
import t3b.pv.cierraturno.dto.EstadisticasDto;
import t3b.pv.cierraturno.dto.HoraTipoDto;
import t3b.pv.cierraturno.dto.InetErrorSummary;
import t3b.pv.cierraturno.dto.IngresoVentasDto;
import t3b.pv.cierraturno.dto.InternetErrorDto;
import t3b.pv.cierraturno.dto.Log10TransDto;
import t3b.pv.cierraturno.dto.LogPtTransDto;
import t3b.pv.cierraturno.dto.LogTregaloDTo;
import t3b.pv.cierraturno.dto.MovDetDto;
import t3b.pv.cierraturno.dto.MovEncDto;
import t3b.pv.cierraturno.dto.MovTregaloDto;
import t3b.pv.cierraturno.dto.MovimientosEvaleDto;
import t3b.pv.cierraturno.dto.MovimientosRetirosDto;
import t3b.pv.cierraturno.dto.MvtosElectroDto;
import t3b.pv.cierraturno.dto.PagosVentasDto;
import t3b.pv.cierraturno.dto.TiendaDto;
import t3b.pv.cierraturno.dto.TpvTicketError;
import t3b.pv.cierraturno.dto.TrnTxDetDto;
import t3b.pv.cierraturno.dto.TurnoDto;
import t3b.pv.cierraturno.dto.VentasArticulosDto;

public interface ConsultasMySql {
	
	public abstract void setConexion(Connection mysql);
	public abstract List<TurnoDto> consultaTurnos();
	public abstract List<DtoTurnoActivo> validaTurnoActivo(int idTurno);
	public abstract void actualizaInfoTurnoReenvio(int idTurno);
	public abstract List<TurnoDto> getInfoTurnoOpenBot();
	public abstract void actualizaInfoDevoluciones(int idTurno, int iddevolucion);
	public abstract void actualizaInfoDevEnc(int idTurno, int idfolio);
	public abstract List<DevolucionesDto> getInfoDevoluciones(int idturno);
	public abstract List<DevolucionesEncabezado> getInfoDevolucionesEnc(int idturno);
	public abstract List<TrnTxDetDto> getInfoTrnTxDet(String clave, String caja, String fecha, int idturno);
	public abstract List<HoraTipoDto> getInfoHoraTipo(String clave, int idturno, String fecha);
	public abstract List<IngresoVentasDto> getInfoIngresoVtas(String clave, String caja, String fecha, int idturno);
	public abstract List<EValeLogDto> getInfoEvaleLog(String clave, String caja, String fecha, int idturno);
	public abstract List<InetErrorSummary> getInfoInetErrorSummary(String clave, String caja, String fecha, int idturno);
	public abstract List<InternetErrorDto> getInfoInetError(String clave, String caja, String fecha, int idturno);
	public abstract List<PagosVentasDto> getInfoPagosVenta(String clave, String caja, String fecha, int idturno);
	public abstract List<MovimientosEvaleDto> getInfoMovsEvale(String clave, String caja, String fecha, int idturno);
	public abstract List<MovimientosRetirosDto> getInfoMovsRetiro(String clave, String caja, String fecha, int idturno);
	public abstract List<TpvTicketError> getInfoTcksError(String clave, String caja, String fecha, int idturno);
	public abstract List<TiendaDto> getNumTienda();
	public abstract List<CancelacionesDto> getInfoCancelaciones(int idTurno);
	public abstract List<CancelacionesEncDto> getInfoCancelacionesEnc(int idTurno);
	public abstract List<CierraTurnoDto> getInfoCierraTurno(int idTurno);
	public abstract List<MovEncDto> getInfoMovEnc(String clave, String caja, String fecha, int idturno);
	public abstract List<Log10TransDto> getInfoLog10Trans(String clave, String caja, String fecha, int idturno);
	public abstract List<LogTregaloDTo> getInfoLogTregalo(String clave, String caja, String fecha, int idturno);
	public abstract List<MovTregaloDto> getInfoMovTRegalo(String clave, String caja, String fecha, int idturno);
	public abstract List<LogPtTransDto> getInfoLogTrans(String clave, String caja, String fecha, int idturno);
	public abstract List<MvtosElectroDto> getInfoMtosElctro(String clave, String caja, String fecha, int idturno);
	public abstract List<VentasArticulosDto> getInfoVtasArti(String clave, String caja, String fecha, int idturno);
	public abstract List<MovDetDto> getInfoMovDet(String clave, String caja, String fecha, int idturno);
	public abstract List<CierraTurnoKardex> getInfoCierraTurnoKardex(int idTurno);
	public abstract void actualizaTurno(int idTurno);
	public abstract void actualizaKardex(int idTurno);
	public abstract List<TurnoDto> getInfoTurno(int idTurno);
	public abstract void actualizaCancelaciones(int idTurno);
	public abstract void actualizaCancelacionesEnc(int idTurno);
	public abstract List<EstadisticasDto> getInfoEstadisticas(int idTurno);
	public abstract void actualizaEstadisticas(int idTurno);
	public abstract void actualizaStatusTurno(int idTurno);
	public abstract List<ArqueoCierraTurnoDto> getInfoArqueoCierraTurno(int idTurno);
	public abstract boolean reestructuraTurno(int idTurno, String caja, String tclave, int userIdCierre);
	public abstract List<ArqueoCierraTurnoDto> recalculoInfoTurnoArqueo(int idTurno, String tienda, String caja);
	
}
